sonar.projectKey=cloudfoundry_multiapps
sonar.organization=cloudfoundry
sonar.projectName="MultiApps Parent"


sonar.exclusions=\
    multiapps-coverage/**

sonar.coverage.exclusions=\
    multiapps-common-test/**
